project:
  type: website

website:
  title: "[PROTOTYPE] The UCSF Wynton Blog"
  
  site-url: https://blog.wynton.ucsf.edu

  description: "The UCSF Wynton Blog (prototype only - nothing to see)"

  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ucsf-wynton/wynton-blog
      - icon: rss
        href: index.xml

  draft-mode: visible

  repo-url: https://github.com/ucsf-wynton/wynton-blog
  repo-actions: [edit, source]
  
format:
  html:
    theme: cosmo
    css:
    - assets/css/this_site.css

execute:
  freeze: auto

draft-mode: visible

resources:
  - CNAME
